fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=10000]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.0
    hooks:
      - id: nbqa-pyupgrade
        args: [--py36-plus]
      - id: nbqa-check-ast
      - id: nbqa-isort
      - id: nbqa-yapf
        args:
          - --in-place
          - --verbose
          - --parallel
          - --recursive
          - --style=google
      - id: nbqa-flake8
        args:
          - --max-line-length=80

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        files: \.ipynb|\.py$
        args:
          - --verbose
          - --errors-only
          - -d duplicate-code
          - --max-line-length=80

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
      - id: yapf
        args:
          - --in-place
          - --verbose
          - --parallel
          - --recursive
          - --style=google
          - column_limit=80

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/myint/autoflake.git
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variable
