repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-case-conflict
      - id: check-added-large-files
        args: [--maxkb=10000]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.0
    hooks:
      - id: nbqa-pyupgrade
        args: [--py36-plus]
      # - id: nbqa-isort
      - id: nbqa-check-ast
      - id: nbqa-black
        args:
          - -v
          - --line-length=80
          - --skip-string-normalization
      - id: nbqa-flake8
        args:
          - --max-line-length=80
      - id: nbqa-pylint
        args:
          - --errors-only
          - --disable=E0401
      # - id: nbqa-yapf
      # - id: nbqa-autopep8

  - repo: https://github.com/pycqa/pylint
    rev: v2.10.2
    hooks:
      - id: pylint
        args:
          - --errors-only
          - -d duplicate-code
          - --disable=E0401

  # - repo: https://github.com/psf/black
  #   rev: 21.8b0
  #   hooks:
  #     - id: black
  #       args:
  #         - -v
  #         - --line-length=80
  #         - --skip-string-normalization

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
      - id: yapf
        args:
          [--in-place, --verbose, --parallel, --recursive, --style=google, column_limit=80]
          # ['--style=.style.yapf', '--parallel', '--in-place']


  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/myint/autoflake.git
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variable

  - repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
      - id: dead

  # - repo: local
  #   hooks:
  #     - id: pytest-check
  #       name: pytest-check
  #       entry: pytest
  #       language: system
  #       pass_filenames: false
  #       always_run: true
