name: jz-test

channels:
  - conda-forge
  - defaults

dependencies:
 - python=3.9.6
 - pandas
 - numpy
 - scikit-learn
 - jupyter
 - requests
 - tensorflow
 - matplotlib
 - click
 - pre-commit
 - pylint=2.10.2
 - pytest
 - nbqa
